### PR TITLE
Multiple app updates (GoTyme, LANDBANK, PalawanPay, Wattpad, Shopee PH)

### PR DESCRIPTION
**Pull request by Hawksprey420**
### <h1>What's new in this pull request:</h1>

<h2>Added app/s:</h2>

### **GoTyme**
- Added app behavior, Android OS version compatibility

### **LANDBANK**
- Added app behavior, Android OS version compatibility

### **Wattpad**
- Added app behavior, Android OS version compatibility'

<h2>Updated app/s:</h2>

### **PalawanPay:**
  - Word changes to app behavior description
  
### **Shopee PH:**
  - Word changes to app behavior description
  
 ---
 ### Changelogs:

| Application | Latest tested version | Android versions | Support level | Known Issues | Notes |
|-------------|-----------------------|------------------|-------------------|------------------|----------|
| GoTyme | 1.36.0 | 13 | ❌ | App crashes immediately upon launching the app
| LANDBANK | 6.1.1 | 13 | ✅ | The app runs for the most part, however, during the user signing up for a bank account, it alerts you to `Error: The device is incompatible with the SDK` when verifying the identity of the user signing up
| PalawanPay | 1.0.4634210 | 13 | ❌ | Starting in this version, Google Play will alert you with "This app won't work for your device" and if you sideloaded an older version of the app, the app prompts you to update but when you press "Update app", it takes you to the Google Play listing, it only lets you uninstall it, or open the app.
| Shopee (PH) | 3.35.31 | 13, 11 | ⚠️ | Any login attempt, even if Magisk DenyList is enabled for Shopee PH, would result in a ``Login Failed (F13) error: Oops, your account has been restricted due to unusual activities. Please make sure you comply with Shopee policies.`` Google login requires GMS installed (use Email or Facebook login as alternatives). Banner information is stretched horizontally
| Wattpad | 10.44.0 | 13 | ✅ | *The Wattpad version tested in this WSA install (Magisk with GMS) is a modded one (no ads).* App works, including the theming and responsive design based on the window size. Online sign in works as well (tested using Facebook SSO), along with offline reading support.

### CODE REVIEW

**Comment by Hawksprey420** [comment]
@infyProductions 
Hi, can I also confirm if Shopee PH also has SafetyNet or Play Integrity checks on your end too, since this is a behavior I have been seeing for a long time already

**Review by riverar — APPROVED** [review]

**Comment by Hawksprey420** [comment]
That's scary fast @riverar but thank you!

**Comment by riverar** [comment]
he watches from ę̸̢̡͙̫̱̘̮̼̱̦̘̯͚͈́̒̿͆̔͐͐̓͌̐̚̚v̵̢̢̺̹̱̀͂͒̿͗̍̾͜ȩ̷̡̧̣̮̪͈͎̞̮̯̩͔̟̞̗̲̐̇̽̈́̆̀̿̄̏̑́̃̐͂͆̒͝ŗ̸̨̳̠̗̪͈̜̱̼̮̓͂̄͒̔̾͋̚͘͝y̴̡̖͕͚̞͖̤̖̦͐̈́͊̈́̀̓̃̚̕ẅ̵̧͖̻̜̼̫̹̳̈́͝ḫ̵̛̲͚̦̯̥̆̋͑̓͗̂̚͘ȩ̴̢̨̘͙̻̖̘̥̬̝̼̬̼̱̮̇̒̍͌̈͗̐̓̈́̋͑͘͘̚͝ř̴̬͙̤͔̉e̵͕͈̓͌́͋̋͑̏̉̉̿͘͘͝͠

**Comment by infyProductions** [comment]
> @infyProductions Hi, can I also confirm if Shopee PH also has SafetyNet or Play Integrity checks on your end too, since this is a behavior I have been seeing for a long time already

I'll test it out later for Shopee PH on my setup (might include Lazada PH, and GCash [since it's been a while, the latest for context is 5.8.1.0])

**Comment by Hawksprey420** [comment]
> > @infyProductions Hi, can I also confirm if Shopee PH also has SafetyNet or Play Integrity checks on your end too, since this is a behavior I have been seeing for a long time already
> 
> I'll test it out later for Shopee PH on my setup (might include Lazada PH, and GCash [since it's been a while, the latest for context is 5.8.1.0])

Lazada PH actually works, but still had the weird scaling issues, as for Gcash, even DenyList wouldn't help much.

Idk, maybe I'm approaching this at a stock WSA + Magisk (GMS) level

**Comment by infyProductions** [comment]
> > > @infyProductions Hi, can I also confirm if Shopee PH also has SafetyNet or Play Integrity checks on your end too, since this is a behavior I have been seeing for a long time already
> > 
> > 
> > I'll test it out later for Shopee PH on my setup (might include Lazada PH, and GCash [since it's been a while, the latest for context is 5.8.1.0])
> 
> Lazada PH actually works, but still had the weird scaling issues, as for Gcash, even DenyList wouldn't help much.
> 
> Idk, maybe I'm approaching this at a stock WSA + Magisk (GMS) level

GCash is a lost cause for me (even tried LSPosed, still stuck at the gcash splash screen) (mine is also WSA + Magisk (GMS) but with LSPosed to hide developer options detection)
I'll add some image links for both lazada and shopee.

**Pull request merged**
