### PR TITLE
Added some entries, fixed information of some entries, rearranged som…

### PR DESCRIPTION
**Pull request by DTD369**
…e entries so they're in alphabetical order

### CODE REVIEW

**Comment by DTD369** [comment]
I accidentally closed the pull request, so I reopened it now 😅

**Comment by riverar** [comment]
Hey @DTD369, when you get a chance can you take a look at the conflict here?

**Comment by DTD369** [comment]
Conflict resolved.

**Comment by riverar** [comment]
Thanks a bunch!

**Pull request merged**
